// Massive word bank: 100 entries per category with 1-word hints for Camo Dude

const CATEGORIES = [
  {
    id: "animals",
    name: "Animals 🦁",
    icon: "🦁",
    words: [
      { secret: "Elephant", hint: "Mammal" },
      { secret: "Dolphin", hint: "Ocean" },
      { secret: "Penguin", hint: "Bird" },
      { secret: "Kangaroo", hint: "Pouch" },
      { secret: "Tyrannosaurus Rex", hint: "Dinosaur" },
      { secret: "Eagle", hint: "Predator" },
      { secret: "Cheetah", hint: "Feline" },
      { secret: "Octopus", hint: "Tentacles" },
      { secret: "Giraffe", hint: "Safari" },
      { secret: "Chameleon", hint: "Reptile" },
      { secret: "Grizzly Bear", hint: "Forest" },
      { secret: "Shark", hint: "Marine" },
      { secret: "Flamingo", hint: "Pink" },
      { secret: "Koala", hint: "Eucalyptus" },
      { secret: "Sloth", hint: "Slow" },
      { secret: "King Cobra", hint: "Venomous" },
      { secret: "Timber Wolf", hint: "Pack" },
      { secret: "Platypus", hint: "Egg" },
      { secret: "Beaver", hint: "Dam" },
      { secret: "Peacock", hint: "Feathers" },
      { secret: "Hippopotamus", hint: "River" },
      { secret: "Chimpanzee", hint: "Primate" },
      { secret: "Crocodile", hint: "Swamp" },
      { secret: "Hedgehog", hint: "Spikes" },
      { secret: "Chinchilla", hint: "Fur" },
      { secret: "Gorilla", hint: "Jungle" },
      { secret: "Panda", hint: "Bamboo" },
      { secret: "Lion", hint: "Roar" },
      { secret: "Tiger", hint: "Stripes" },
      { secret: "Zebra", hint: "Black-and-white" },
      { secret: "Rhinoceros", hint: "Horn" },
      { secret: "Polar Bear", hint: "Arctic" },
      { secret: "Camel", hint: "Hump" },
      { secret: "Llama", hint: "Wool" },
      { secret: "Walrus", hint: "Tusks" },
      { secret: "Seahorse", hint: "Coral" },
      { secret: "Jellyfish", hint: "Sting" },
      { secret: "Stingray", hint: "Flat" },
      { secret: "Blue Whale", hint: "Giant" },
      { secret: "Hummingbird", hint: "Tiny" },
      { secret: "Owl", hint: "Nocturnal" },
      { secret: "Falcon", hint: "Fast" },
      { secret: "Pelican", hint: "Beak" },
      { secret: "Toucan", hint: "Tropical" },
      { secret: "Parrot", hint: "Feathers" },
      { secret: "Ostrich", hint: "Tall" },
      { secret: "Komodo Dragon", hint: "Lizard" },
      { secret: "Iguana", hint: "Scales" },
      { secret: "Gecko", hint: "Sticky" },
      { secret: "Chameleon", hint: "Camouflage" },
      { secret: "Alligator", hint: "Jaws" },
      { secret: "Sea Turtle", hint: "Shell" },
      { secret: "Frog", hint: "Amphibian" },
      { secret: "Salamander", hint: "Moist" },
      { secret: "Axolotl", hint: "Gill" },
      { secret: "Otter", hint: "River" },
      { secret: "Meerkat", hint: "Burrow" },
      { secret: "Lemur", hint: "Tail" },
      { secret: "Baboon", hint: "Monkey" },
      { secret: "Orangutan", hint: "Ape" },
      { secret: "Gibbon", hint: "Swinging" },
      { secret: "Snow Leopard", hint: "Mountains" },
      { secret: "Jaguar", hint: "Spots" },
      { secret: "Panther", hint: "Dark" },
      { secret: "Puma", hint: "Mountain" },
      { secret: "Hyena", hint: "Scavenger" },
      { secret: "Fox", hint: "Cunning" },
      { secret: "Coyote", hint: "Howl" },
      { secret: "Dingo", hint: "Wild" },
      { secret: "Badger", hint: "Burrower" },
      { secret: "Wolverine", hint: "Fierce" },
      { secret: "Skunk", hint: "Smell" },
      { secret: "Raccoon", hint: "Mask" },
      { secret: "Opossum", hint: "Marsupial" },
      { secret: "Armadillo", hint: "Armor" },
      { secret: "Porcupine", hint: "Quills" },
      { secret: "Capybara", hint: "Rodent" },
      { secret: "Hamster", hint: "Cheeks" },
      { secret: "Guinea Pig", hint: "Pet" },
      { secret: "Ferret", hint: "Weasel" },
      { secret: "Mole", hint: "Underground" },
      { secret: "Bat", hint: "Wings" },
      { secret: "Flying Squirrel", hint: "Glider" },
      { secret: "Antelope", hint: "Horns" },
      { secret: "Gazelle", hint: "Graceful" },
      { secret: "Moose", hint: "Antlers" },
      { secret: "Reindeer", hint: "Sleigh" },
      { secret: "Bison", hint: "Buffalo" },
      { secret: "Yak", hint: "Himalayas" },
      { secret: "Wild Boar", hint: "Tusks" },
      { secret: "Tapir", hint: "Trunk" },
      { secret: "Manatee", hint: "Cow" },
      { secret: "Narwhal", hint: "Unicorn" },
      { secret: "Orca", hint: "Killer" },
      { secret: "Lobster", hint: "Claws" },
      { secret: "Crab", hint: "Pinch" },
      { secret: "Squid", hint: "Ink" },
      { secret: "Chameleon Lizard", hint: "Blend" },
      { secret: "Tarantula", hint: "Spider" },
      { secret: "Scorpion", hint: "Stinger" }
    ]
  },
  {
    id: "school_subjects",
    name: "School Subjects 📚",
    icon: "📚",
    words: [
      { secret: "Mathematics", hint: "Numbers" },
      { secret: "Science", hint: "Experiments" },
      { secret: "Geography", hint: "Maps" },
      { secret: "Art Class", hint: "Drawing" },
      { secret: "Physical Education", hint: "Fitness" },
      { secret: "Backpack", hint: "Bag" },
      { secret: "Microscope", hint: "Laboratory" },
      { secret: "Calculator", hint: "Math" },
      { secret: "Library", hint: "Books" },
      { secret: "History", hint: "Past" },
      { secret: "Music Class", hint: "Instruments" },
      { secret: "Dictionary", hint: "Definitions" },
      { secret: "Compass", hint: "Direction" },
      { secret: "Protractor", hint: "Angles" },
      { secret: "Laptop", hint: "Computer" },
      { secret: "Textbook", hint: "Reading" },
      { secret: "Cafeteria", hint: "Lunch" },
      { secret: "Principal", hint: "Leader" },
      { secret: "Recess", hint: "Playground" },
      { secret: "Blackboard", hint: "Chalk" },
      { secret: "Crayons", hint: "Coloring" },
      { secret: "Drama Class", hint: "Acting" },
      { secret: "Spelling Bee", hint: "Words" },
      { secret: "Globe", hint: "Sphere" },
      { secret: "Telescope", hint: "Stars" },
      { secret: "Biology", hint: "Life" },
      { secret: "Chemistry", hint: "Molecules" },
      { secret: "Physics", hint: "Motion" },
      { secret: "Geometry", hint: "Shapes" },
      { secret: "Algebra", hint: "Variables" },
      { secret: "Calculus", hint: "Derivatives" },
      { secret: "Literature", hint: "Novels" },
      { secret: "Grammar", hint: "Punctuation" },
      { secret: "Spanish Class", hint: "Language" },
      { secret: "French Class", hint: "Language" },
      { secret: "Coding", hint: "Software" },
      { secret: "Robotics", hint: "Automation" },
      { secret: "Astronomy", hint: "Galaxies" },
      { secret: "Geology", hint: "Rocks" },
      { secret: "Psychology", hint: "Mind" },
      { secret: "Economics", hint: "Finance" },
      { secret: "Sociology", hint: "Society" },
      { secret: "Philosophy", hint: "Ethics" },
      { secret: "Journalism", hint: "Reporting" },
      { secret: "Woodshop", hint: "Carpentry" },
      { secret: "Home Economics", hint: "Cooking" },
      { secret: "Band Class", hint: "Brass" },
      { secret: "Choir", hint: "Singing" },
      { secret: "Orchestra", hint: "Strings" },
      { secret: "Pencil", hint: "Graphite" },
      { secret: "Eraser", hint: "Rubber" },
      { secret: "Notebook", hint: "Paper" },
      { secret: "Highlighter", hint: "Neon" },
      { secret: "Ruler", hint: "Measurement" },
      { secret: "Scissors", hint: "Cutting" },
      { secret: "Glue Stick", hint: "Adhesive" },
      { secret: "Stapler", hint: "Fastener" },
      { secret: "Folder", hint: "Organizer" },
      { secret: "Binder", hint: "Rings" },
      { secret: "Desk", hint: "Furniture" },
      { secret: "Whiteboard", hint: "Marker" },
      { secret: "Locker", hint: "Storage" },
      { secret: "Gymnasium", hint: "Sports" },
      { secret: "Auditorium", hint: "Stage" },
      { secret: "Hallway", hint: "Corridor" },
      { secret: "Report Card", hint: "Grades" },
      { secret: "Diploma", hint: "Graduation" },
      { secret: "Homework", hint: "Assignment" },
      { secret: "Pop Quiz", hint: "Test" },
      { secret: "Midterm Exam", hint: "Assessment" },
      { secret: "Final Exam", hint: "Testing" },
      { secret: "Science Fair", hint: "Poster" },
      { secret: "Yearbook", hint: "Photos" },
      { secret: "Field Trip", hint: "Excursion" },
      { secret: "School Bus", hint: "Transit" },
      { secret: "Mascot", hint: "Costume" },
      { secret: "Hall Pass", hint: "Permit" },
      { secret: "Detention", hint: "Punishment" },
      { secret: "Substitute Teacher", hint: "Replacement" },
      { secret: "Tutor", hint: "Help" },
      { secret: "Classroom", hint: "Learning" },
      { secret: "Lecture", hint: "Presentation" },
      { secret: "Essay", hint: "Writing" },
      { secret: "Poetry", hint: "Rhyme" },
      { secret: "Vocabulary", hint: "Words" },
      { secret: "Fractions", hint: "Division" },
      { secret: "Decimals", hint: "Points" },
      { secret: "Equations", hint: "Algebra" },
      { secret: "Periodic Table", hint: "Elements" },
      { secret: "DNA", hint: "Genetics" },
      { secret: "Photosynthesis", hint: "Plants" },
      { secret: "Gravity", hint: "Force" },
      { secret: "Ecosystem", hint: "Nature" },
      { secret: "Fossils", hint: "Prehistoric" },
      { secret: "Latitude", hint: "Lines" },
      { secret: "Longitude", hint: "Grid" },
      { secret: "Continents", hint: "Landmasses" },
      { secret: "Oceanography", hint: "Seas" },
      { secret: "Meteorology", hint: "Weather" }
    ]
  },
  {
    id: "food_treats",
    name: "Food & Treats 🍕",
    icon: "🍕",
    words: [
      { secret: "Pizza", hint: "Cheese" },
      { secret: "Ice Cream", hint: "Dessert" },
      { secret: "Spaghetti", hint: "Pasta" },
      { secret: "Hamburger", hint: "Sandwich" },
      { secret: "Watermelon", hint: "Fruit" },
      { secret: "Pancakes", hint: "Breakfast" },
      { secret: "Tacos", hint: "Mexican" },
      { secret: "Cupcake", hint: "Bakery" },
      { secret: "Popcorn", hint: "Snack" },
      { secret: "French Fries", hint: "Potatoes" },
      { secret: "Chocolate", hint: "Sweet" },
      { secret: "Sushi", hint: "Seafood" },
      { secret: "Glazed Donut", hint: "Pastry" },
      { secret: "Hot Dog", hint: "Stadium" },
      { secret: "Waffles", hint: "Syrup" },
      { secret: "Pretzel", hint: "Salty" },
      { secret: "Pineapple", hint: "Tropical" },
      { secret: "Crispy Bacon", hint: "Breakfast" },
      { secret: "Loaded Nachos", hint: "Tortilla" },
      { secret: "Fruit Smoothie", hint: "Blended" },
      { secret: "Cheesecake", hint: "Dairy" },
      { secret: "Bean Burrito", hint: "Wrap" },
      { secret: "Cotton Candy", hint: "Fair" },
      { secret: "Steamed Dumplings", hint: "Asian" },
      { secret: "Meatballs", hint: "Sauce" },
      { secret: "Apple Pie", hint: "Cinnamon" },
      { secret: "Chocolate Chip Cookie", hint: "Baking" },
      { secret: "Brownie", hint: "Fudge" },
      { secret: "Churros", hint: "Sugar" },
      { secret: "Macaroni and Cheese", hint: "Cheddar" },
      { secret: "Grilled Cheese", hint: "Toast" },
      { secret: "Chicken Nuggets", hint: "Dipping" },
      { secret: "Barbecue Ribs", hint: "Smoky" },
      { secret: "Steak", hint: "Grill" },
      { secret: "Fried Chicken", hint: "Crispy" },
      { secret: "Lasagna", hint: "Layers" },
      { secret: "Ramen", hint: "Noodles" },
      { secret: "Pho", hint: "Broth" },
      { secret: "Quesadilla", hint: "Melted" },
      { secret: "Guacamole", hint: "Avocado" },
      { secret: "Salsa", hint: "Dip" },
      { secret: "Garlic Bread", hint: "Butter" },
      { secret: "Mashed Potatoes", hint: "Gravy" },
      { secret: "Onion Rings", hint: "Battered" },
      { secret: "Clam Chowder", hint: "Soup" },
      { secret: "Tomato Soup", hint: "Bowl" },
      { secret: "Caesar Salad", hint: "Croutons" },
      { secret: "Fruit Salad", hint: "Berries" },
      { secret: "Strawberry", hint: "Red" },
      { secret: "Banana", hint: "Peel" },
      { secret: "Mango", hint: "Juicy" },
      { secret: "Grapes", hint: "Vine" },
      { secret: "Peach", hint: "Fuzzy" },
      { secret: "Blueberry", hint: "Antioxidant" },
      { secret: "Cherries", hint: "Pits" },
      { secret: "Avocado", hint: "Green" },
      { secret: "Broccoli", hint: "Vegetable" },
      { secret: "Carrot", hint: "Orange" },
      { secret: "Sweet Corn", hint: "Cob" },
      { secret: "Popcorn Chicken", hint: "Bite-sized" },
      { secret: "French Toast", hint: "Brioche" },
      { secret: "Bagel", hint: "Cream-cheese" },
      { secret: "Croissant", hint: "Flaky" },
      { secret: "Muffin", hint: "Blueberry" },
      { secret: "Omelet", hint: "Eggs" },
      { secret: "Cereal", hint: "Milk" },
      { secret: "Oatmeal", hint: "Oats" },
      { secret: "Yogurt", hint: "Probiotic" },
      { secret: "Marshmallow", hint: "Fluffy" },
      { secret: "S'mores", hint: "Campfire" },
      { secret: "Gummy Bears", hint: "Candy" },
      { secret: "Lollipop", hint: "Stick" },
      { secret: "Jelly Beans", hint: "Assorted" },
      { secret: "Peanut Butter", hint: "Spread" },
      { secret: "Nutella", hint: "Hazelnut" },
      { secret: "Popsicle", hint: "Frozen" },
      { secret: "Sundae", hint: "Hot-fudge" },
      { secret: "Milkshake", hint: "Diner" },
      { secret: "Lemonade", hint: "Citrus" },
      { secret: "Iced Tea", hint: "Refreshing" },
      { secret: "Hot Chocolate", hint: "Cocoa" },
      { secret: "Bubble Tea", hint: "Boba" },
      { secret: "Espresso", hint: "Coffee" },
      { secret: "Pecan Pie", hint: "Nuts" },
      { secret: "Macarons", hint: "French" },
      { secret: "Eclair", hint: "Cream" },
      { secret: "Gelato", hint: "Italian" },
      { secret: "Fondue", hint: "Dipper" },
      { secret: "Spring Rolls", hint: "Crispy" },
      { secret: "Teriyaki Chicken", hint: "Glaze" },
      { secret: "Curry", hint: "Spices" },
      { secret: "Paella", hint: "Saffron" },
      { secret: "Empanada", hint: "Pastry" },
      { secret: "Hummus", hint: "Chickpeas" },
      { secret: "Pita Bread", hint: "Pocket" },
      { secret: "Falafel", hint: "Fried" },
      { secret: "Kebabs", hint: "Skewers" },
      { secret: "Baklava", hint: "Honey" },
      { secret: "Clam Bake", hint: "Seafood" }
    ]
  },
  {
    id: "jobs_careers",
    name: "Jobs & Careers 👩‍🚀",
    icon: "👩‍🚀",
    words: [
      { secret: "Astronaut", hint: "Spacecraft" },
      { secret: "Firefighter", hint: "Rescue" },
      { secret: "Veterinarian", hint: "Animals" },
      { secret: "Chef", hint: "Cooking" },
      { secret: "Pilot", hint: "Airplane" },
      { secret: "Police Officer", hint: "Safety" },
      { secret: "Architect", hint: "Buildings" },
      { secret: "Scientist", hint: "Research" },
      { secret: "Detective", hint: "Investigation" },
      { secret: "Musician", hint: "Songs" },
      { secret: "Athlete", hint: "Sports" },
      { secret: "Teacher", hint: "Classroom" },
      { secret: "Surgeon", hint: "Hospital" },
      { secret: "Electrician", hint: "Wiring" },
      { secret: "Judge", hint: "Courtroom" },
      { secret: "Photographer", hint: "Camera" },
      { secret: "Farmer", hint: "Agriculture" },
      { secret: "Plumber", hint: "Pipes" },
      { secret: "Dentist", hint: "Teeth" },
      { secret: "Marine Biologist", hint: "Ocean" },
      { secret: "Journalist", hint: "News" },
      { secret: "Mechanic", hint: "Engines" },
      { secret: "Librarian", hint: "Catalog" },
      { secret: "Baker", hint: "Oven" },
      { secret: "Archeologist", hint: "Fossils" },
      { secret: "Software Engineer", hint: "Code" },
      { secret: "Graphic Designer", hint: "Visuals" },
      { secret: "Video Game Developer", hint: "Gaming" },
      { secret: "Pilot", hint: "Aviation" },
      { secret: "Flight Attendant", hint: "Cabin" },
      { secret: "Paramedic", hint: "Ambulance" },
      { secret: "Nurse", hint: "Care" },
      { secret: "Pharmacist", hint: "Medicine" },
      { secret: "Optometrist", hint: "Vision" },
      { secret: "Physical Therapist", hint: "Rehabilitation" },
      { secret: "Psychiatrist", hint: "Mental" },
      { secret: "Lawyer", hint: "Legal" },
      { secret: "Paralegal", hint: "Documents" },
      { secret: "Politician", hint: "Government" },
      { secret: "Mayor", hint: "City" },
      { secret: "Governor", hint: "State" },
      { secret: "Diplomat", hint: "Embassy" },
      { secret: "Commercial Diver", hint: "Underwater" },
      { secret: "Coast Guard", hint: "Maritime" },
      { secret: "Soldier", hint: "Military" },
      { secret: "Park Ranger", hint: "Wilderness" },
      { secret: "Conservationist", hint: "Ecology" },
      { secret: "Zoologist", hint: "Wildlife" },
      { secret: "Botanist", hint: "Flora" },
      { secret: "Astronomer", hint: "Telescope" },
      { secret: "Geologist", hint: "Rocks" },
      { secret: "Meteorologist", hint: "Forecast" },
      { secret: "Chemist", hint: "Molecules" },
      { secret: "Physicist", hint: "Atoms" },
      { secret: "Banker", hint: "Finance" },
      { secret: "Accountant", hint: "Taxes" },
      { secret: "Stock Broker", hint: "Trading" },
      { secret: "Real Estate Agent", hint: "Houses" },
      { secret: "Interior Designer", hint: "Decor" },
      { secret: "Landscape Architect", hint: "Gardens" },
      { secret: "Construction Worker", hint: "Hardhat" },
      { secret: "Welder", hint: "Sparks" },
      { secret: "Carpenter", hint: "Woodwork" },
      { secret: "Blacksmith", hint: "Anvil" },
      { secret: "Machinist", hint: "Lathe" },
      { secret: "Automotive Engineer", hint: "Vehicles" },
      { secret: "Train Conductor", hint: "Locomotive" },
      { secret: "Bus Driver", hint: "Transit" },
      { secret: "Ship Captain", hint: "Vessel" },
      { secret: "Deep Sea Fisherman", hint: "Net" },
      { secret: "Barista", hint: "Espresso" },
      { secret: "Sommelier", hint: "Tasting" },
      { secret: "Florist", hint: "Bouquet" },
      { secret: "Hair Stylist", hint: "Scissors" },
      { secret: "Makeup Artist", hint: "Cosmetics" },
      { secret: "Fashion Designer", hint: "Runway" },
      { secret: "Model", hint: "Photoshoot" },
      { secret: "Actor", hint: "Hollywood" },
      { secret: "Movie Director", hint: "Film" },
      { secret: "Stunt Double", hint: "Action" },
      { secret: "Voice Actor", hint: "Microphone" },
      { secret: "Audio Engineer", hint: "Soundboard" },
      { secret: "Conductor", hint: "Symphony" },
      { secret: "Dancer", hint: "Choreography" },
      { secret: "Comedian", hint: "Humor" },
      { secret: "Magician", hint: "Illusion" },
      { secret: "Circus Acrobat", hint: "Trapeze" },
      { secret: "Personal Trainer", hint: "Fitness" },
      { secret: "Lifeguard", hint: "Poolside" },
      { secret: "Ski Instructor", hint: "Slopes" },
      { secret: "Tour Guide", hint: "Sightseeing" },
      { secret: "Translator", hint: "Languages" },
      { secret: "Author", hint: "Books" },
      { secret: "Poet", hint: "Verses" },
      { secret: "Editor", hint: "Publishing" },
      { secret: "Event Planner", hint: "Parties" },
      { secret: "Hotel Manager", hint: "Hospitality" },
      { secret: "Flight Engineer", hint: "Aircraft" },
      { secret: "Flight Controler", hint: "Tower" },
      { secret: "Cryptographer", hint: "Ciphers" }
    ]
  },
  {
    id: "sports_games",
    name: "Sports & Games 🏀",
    icon: "🏀",
    words: [
      { secret: "Basketball", hint: "Dribble" },
      { secret: "Soccer", hint: "Kicking" },
      { secret: "Swimming", hint: "Water" },
      { secret: "Gymnastics", hint: "Acrobatics" },
      { secret: "Skateboarding", hint: "Wheels" },
      { secret: "Ice Hockey", hint: "Rink" },
      { secret: "Baseball", hint: "Diamond" },
      { secret: "Tennis", hint: "Racket" },
      { secret: "Camping", hint: "Outdoors" },
      { secret: "Karate", hint: "Combat" },
      { secret: "Bowling", hint: "Pins" },
      { secret: "Skiing", hint: "Snow" },
      { secret: "Volleyball", hint: "Net" },
      { secret: "Golf", hint: "Course" },
      { secret: "Archery", hint: "Bow" },
      { secret: "Snowboarding", hint: "Mountain" },
      { secret: "Surfing", hint: "Waves" },
      { secret: "Dodgeball", hint: "Throw" },
      { secret: "Rock Climbing", hint: "Harness" },
      { secret: "Cycling", hint: "Bicycle" },
      { secret: "Fencing", hint: "Sword" },
      { secret: "Figure Skating", hint: "Ice" },
      { secret: "Table Tennis", hint: "Paddle" },
      { secret: "Track & Field", hint: "Running" },
      { secret: "Kayaking", hint: "Paddle" },
      { secret: "American Football", hint: "Touchdown" },
      { secret: "Rugby", hint: "Scrum" },
      { secret: "Cricket", hint: "Wicket" },
      { secret: "Lacrosse", hint: "Mesh" },
      { secret: "Badminton", hint: "Shuttlecock" },
      { secret: "Squash", hint: "Racquet" },
      { secret: "Handball", hint: "Court" },
      { secret: "Water Polo", hint: "Pool" },
      { secret: "Synchronized Swimming", hint: "Routine" },
      { secret: "Diving", hint: "Springboard" },
      { secret: "Rowing", hint: "Oars" },
      { secret: "Sailing", hint: "Yacht" },
      { secret: "Windsurfing", hint: "Sailboard" },
      { secret: "Wakeboarding", hint: "Towboat" },
      { secret: "Scuba Diving", hint: "Oxygen" },
      { secret: "Triathlon", hint: "Endurance" },
      { secret: "Marathon", hint: "26-Miles" },
      { secret: "Sprint", hint: "Dash" },
      { secret: "High Jump", hint: "Bar" },
      { secret: "Pole Vault", hint: "Pole" },
      { secret: "Long Jump", hint: "Sandpit" },
      { secret: "Shot Put", hint: "Heavy" },
      { secret: "Javelin", hint: "Spear" },
      { secret: "Weightlifting", hint: "Barbell" },
      { secret: "Powerlifting", hint: "Squat" },
      { secret: "CrossFit", hint: "Workout" },
      { secret: "Boxing", hint: "Gloves" },
      { secret: "Judo", hint: "Tatami" },
      { secret: "Taekwondo", hint: "Kicks" },
      { secret: "Brazilian Jiu-Jitsu", hint: "Grappling" },
      { secret: "Wrestling", hint: "Mat" },
      { secret: "Sumo", hint: "Ring" },
      { secret: "Kickboxing", hint: "Ring" },
      { secret: "Muay Thai", hint: "Elbows" },
      { secret: "BMX", hint: "Ramps" },
      { secret: "Motocross", hint: "Dirtbike" },
      { secret: "Formula 1", hint: "Racecar" },
      { secret: "NASCAR", hint: "Speedway" },
      { secret: "Rally Racing", hint: "Offroad" },
      { secret: "Go-Karting", hint: "Circuit" },
      { secret: "Horse Racing", hint: "Jockey" },
      { secret: "Equestrian", hint: "Jumping" },
      { secret: "Polo", hint: "Mallet" },
      { secret: "Rodeo", hint: "Bull" },
      { secret: "Bobsled", hint: "Ice-track" },
      { secret: "Luge", hint: "Sled" },
      { secret: "Curling", hint: "Broom" },
      { secret: "Speed Skating", hint: "Oval" },
      { secret: "Biathlon", hint: "Rifle" },
      { secret: "Parkour", hint: "Obstacles" },
      { secret: "Frisbee Golf", hint: "Basket" },
      { secret: "Ultimate Frisbee", hint: "Disc" },
      { secret: "Billiards", hint: "Cue" },
      { secret: "Snooker", hint: "Table" },
      { secret: "Darts", hint: "Bullseye" },
      { secret: "Foosball", hint: "Tabletop" },
      { secret: "Air Hockey", hint: "Puck" },
      { secret: "Shuffleboard", hint: "Puck" },
      { secret: "Bocce Ball", hint: "Lawn" },
      { secret: "Croquet", hint: "Mallet" },
      { secret: "Horseshoes", hint: "Pit" },
      { secret: "Cornhole", hint: "Beanbag" },
      { secret: "Pickleball", hint: "Paddle" },
      { secret: "Paddleball", hint: "Wall" },
      { secret: "Racquetball", hint: "Court" },
      { secret: "Laser Tag", hint: "Vest" },
      { secret: "Paintball", hint: "Marker" },
      { secret: "Roller Derby", hint: "Skates" },
      { secret: "Cheerleading", hint: "Pompoms" },
      { secret: "Breakdancing", hint: "Hip-hop" },
      { secret: "Tug of War", hint: "Rope" },
      { secret: "Hacky Sack", hint: "Footbag" },
      { secret: "Slacklining", hint: "Balance" },
      { secret: "Trampolining", hint: "Bounce" },
      { secret: "Bungee Jumping", hint: "Cord" }
    ]
  },
  {
    id: "awesome_places",
    name: "Awesome Places 🏰",
    icon: "🏰",
    words: [
      { secret: "Amusement Park", hint: "Rides" },
      { secret: "Outer Space", hint: "Planets" },
      { secret: "Coral Reef", hint: "Underwater" },
      { secret: "Rainforest", hint: "Jungle" },
      { secret: "Pyramids", hint: "Monuments" },
      { secret: "Volcano", hint: "Lava" },
      { secret: "Airport", hint: "Flights" },
      { secret: "Museum", hint: "Exhibits" },
      { secret: "Zoo Park", hint: "Animals" },
      { secret: "Movie Theater", hint: "Cinema" },
      { secret: "Castle", hint: "Kingdom" },
      { secret: "Tropical Island", hint: "Beach" },
      { secret: "Grand Canyon", hint: "Gorge" },
      { secret: "Space Station", hint: "Orbit" },
      { secret: "Water Park", hint: "Slides" },
      { secret: "Lighthouse", hint: "Coast" },
      { secret: "Aquarium", hint: "Fish" },
      { secret: "Glacier", hint: "Ice" },
      { secret: "Cave", hint: "Underground" },
      { secret: "Stadium", hint: "Arena" },
      { secret: "Hollywood", hint: "Movies" },
      { secret: "Stonehenge", hint: "Monoliths" },
      { secret: "National Park", hint: "Wilderness" },
      { secret: "Venice Canals", hint: "Gondola" },
      { secret: "North Pole", hint: "Arctic" },
      { secret: "Eiffel Tower", hint: "Paris" },
      { secret: "Great Wall of China", hint: "Fortress" },
      { secret: "Taj Mahal", hint: "Marble" },
      { secret: "Colosseum", hint: "Rome" },
      { secret: "Machu Picchu", hint: "Inca" },
      { secret: "Statue of Liberty", hint: "New-York" },
      { secret: "Big Ben", hint: "London" },
      { secret: "Niagara Falls", hint: "Waterfall" },
      { secret: "Mount Everest", hint: "Peak" },
      { secret: "Bermuda Triangle", hint: "Mystery" },
      { secret: "Sahara Desert", hint: "Dunes" },
      { secret: "Amazon River", hint: "South-America" },
      { secret: "Galapagos Islands", hint: "Tortoises" },
      { secret: "Yellowstone", hint: "Geysers" },
      { secret: "Yosemite", hint: "Granite" },
      { secret: "Times Square", hint: "Billboards" },
      { secret: "Golden Gate Bridge", hint: "San-Francisco" },
      { secret: "Mount Fuji", hint: "Japan" },
      { secret: "Sydney Opera House", hint: "Sails" },
      { secret: "Christ the Redeemer", hint: "Brazil" },
      { secret: "Easter Island", hint: "Statues" },
      { secret: "Loch Ness", hint: "Monster" },
      { secret: "Dead Sea", hint: "Salt" },
      { secret: "Antarctica", hint: "Penguins" },
      { secret: "Madagascar", hint: "Lemurs" },
      { secret: "Monaco", hint: "Casinos" },
      { secret: "Las Vegas Strip", hint: "Neon" },
      { secret: "Disneyland", hint: "Theme-park" },
      { secret: "Universal Studios", hint: "Attractions" },
      { secret: "Louvre Museum", hint: "Art" },
      { secret: "Vatican City", hint: "Chapel" },
      { secret: "Acropolis", hint: "Athens" },
      { secret: "Santorini", hint: "White-houses" },
      { secret: "Dubrovnik", hint: "Walls" },
      { secret: "Prague Castle", hint: "Bohemia" },
      { secret: "Neuschwanstein Castle", hint: "Bavaria" },
      { secret: "Alps Mountains", hint: "Peaks" },
      { secret: "Kilimanjaro", hint: "Tanzania" },
      { secret: "Serengeti", hint: "Safari" },
      { secret: "Victoria Falls", hint: "Mist" },
      { secret: "Great Barrier Reef", hint: "Australia" },
      { secret: "Outback", hint: "Kangarooland" },
      { secret: "Fuji Five Lakes", hint: "Volcano" },
      { secret: "Kyoto Gardens", hint: "Shrines" },
      { secret: "Petra", hint: "Carved-stone" },
      { secret: "Burj Khalifa", hint: "Skyscraper" },
      { secret: "Maldives", hint: "Atolls" },
      { secret: "Bora Bora", hint: "Bungalows" },
      { secret: "Fjords", hint: "Norway" },
      { secret: "Northern Lights", hint: "Aurora" },
      { secret: "Iceland Geysers", hint: "Thermal" },
      { secret: "Mount Rushmore", hint: "Presidents" },
      { secret: "Kennedy Space Center", hint: "Rockets" },
      { secret: "Alcatraz", hint: "Island-prison" },
      { secret: "Grand Bazaar", hint: "Market" },
      { secret: "Forbidden City", hint: "Beijing" },
      { secret: "Terracotta Army", hint: "Emperor" },
      { secret: "Gobi Desert", hint: "Asia" },
      { secret: "Everglades", hint: "Swamp" },
      { secret: "Redwood Forest", hint: "Trees" },
      { secret: "Death Valley", hint: "Heat" },
      { secret: "Pike Place Market", hint: "Fish-market" },
      { secret: "French Riviera", hint: "Coastline" },
      { secret: "Ibiza", hint: "Nightlife" },
      { secret: "Swiss Alps", hint: "Chalets" },
      { secret: "Black Forest", hint: "Germany" },
      { secret: "Transylvania", hint: "Dracula" },
      { secret: "Kremlin", hint: "Moscow" },
      { secret: "Panama Canal", hint: "Locks" },
      { secret: "Galapagos Reef", hint: "Diving" },
      { secret: "Patagonia", hint: "Glaciers" },
      { secret: "Atacama Desert", hint: "Stargazing" },
      { secret: "Cenotes", hint: "Sinkholes" },
      { secret: "Mount Rainier", hint: "Washington" },
      { secret: "Space Needle", hint: "Seattle" }
    ]
  },
  {
    id: "games_toys",
    name: "Games & Toys 🎮",
    icon: "🎮",
    words: [
      { secret: "Minecraft", hint: "Building" },
      { secret: "Super Mario", hint: "Plumber" },
      { secret: "Pokémon", hint: "Monsters" },
      { secret: "Roblox", hint: "Gaming" },
      { secret: "Mario Kart", hint: "Racing" },
      { secret: "Zelda Quest", hint: "Adventure" },
      { secret: "LEGO Bricks", hint: "Blocks" },
      { secret: "Superhero", hint: "Powers" },
      { secret: "Comic Book", hint: "Illustrations" },
      { secret: "Board Game", hint: "Tabletop" },
      { secret: "Virtual Reality", hint: "Headset" },
      { secret: "Arcade Machine", hint: "Coins" },
      { secret: "Fortnite", hint: "Battle" },
      { secret: "Tetris", hint: "Blocks" },
      { secret: "Pac-Man", hint: "Ghost" },
      { secret: "Rubik's Cube", hint: "Puzzle" },
      { secret: "Yo-Yo", hint: "String" },
      { secret: "Drone", hint: "Flight" },
      { secret: "Nintendo Switch", hint: "Console" },
      { secret: "Dungeons & Dragons", hint: "Dice" },
      { secret: "Sonic the Hedgehog", hint: "Speed" },
      { secret: "Chess", hint: "Strategy" },
      { secret: "Tamagotchi", hint: "Virtual" },
      { secret: "Hoverboard", hint: "Wheels" },
      { secret: "Hot Wheels", hint: "Tracks" },
      { secret: "Barbie", hint: "Doll" },
      { secret: "G.I. Joe", hint: "Action-figure" },
      { secret: "Transformers", hint: "Robots" },
      { secret: "Play-Doh", hint: "Clay" },
      { secret: "Slinky", hint: "Spring" },
      { secret: "Nerf Blaster", hint: "Foam" },
      { secret: "Super Soaker", hint: "Water" },
      { secret: "Etch A Sketch", hint: "Drawing" },
      { secret: "Hula Hoop", hint: "Spinning" },
      { secret: "Frisbee", hint: "Flying" },
      { secret: "Teddy Bear", hint: "Stuffed" },
      { secret: "Raggedy Ann", hint: "Cloth" },
      { secret: "Cabbage Patch Kids", hint: "Dolls" },
      { secret: "American Girl", hint: "Historical" },
      { secret: "Beanie Babies", hint: "Pellets" },
      { secret: "Polly Pocket", hint: "Compact" },
      { secret: "Bratz", hint: "Fashion" },
      { secret: "Funko Pop", hint: "Collectible" },
      { secret: "Magic 8-Ball", hint: "Fortune" },
      { secret: "Silly Putty", hint: "Bouncy" },
      { secret: "Slime", hint: "Gooey" },
      { secret: "Fingerboard", hint: "Miniature" },
      { secret: "Remote Control Car", hint: "Radio" },
      { secret: "Model Airplane", hint: "Assembly" },
      { secret: "Jigsaw Puzzle", hint: "Pieces" },
      { secret: "Monopoly", hint: "Real-estate" },
      { secret: "Scrabble", hint: "Words" },
      { secret: "Clue", hint: "Mystery" },
      { secret: "Risk", hint: "Conquest" },
      { secret: "Catan", hint: "Settlers" },
      { secret: "Ticket to Ride", hint: "Trains" },
      { secret: "Pandemic", hint: "Cooperative" },
      { secret: "Battleship", hint: "Grid" },
      { secret: "Connect Four", hint: "Grid" },
      { secret: "Jenga", hint: "Tower" },
      { secret: "Operation", hint: "Buzzer" },
      { secret: "Hungry Hungry Hippos", hint: "Marbles" },
      { secret: "Candy Land", hint: "Board" },
      { secret: "Chutes and Ladders", hint: "Climbing" },
      { secret: "Guess Who?", hint: "Faces" },
      { secret: "Sorry!", hint: "Pawns" },
      { secret: "Trouble", hint: "Pop-o-matic" },
      { secret: "Uno", hint: "Cards" },
      { secret: "Phase 10", hint: "Rummy" },
      { secret: "Exploding Kittens", hint: "Card-game" },
      { secret: "Codenames", hint: "Spies" },
      { secret: "Dominos", hint: "Tiles" },
      { secret: "Mahjong", hint: "Tiles" },
      { secret: "Checkers", hint: "Crown" },
      { secret: "Backgammon", hint: "Doubling" },
      { secret: "Go", hint: "Stones" },
      { secret: "Poker", hint: "Chips" },
      { secret: "Blackjack", hint: "Twenty-one" },
      { secret: "Solitaire", hint: "Patience" },
      { secret: "PlayStation", hint: "Sony" },
      { secret: "Xbox", hint: "Microsoft" },
      { secret: "Game Boy", hint: "Handheld" },
      { secret: "Atari", hint: "Joystick" },
      { secret: "Sega Genesis", hint: "Cartridge" },
      { secret: "Donkey Kong", hint: "Barrels" },
      { secret: "Street Fighter", hint: "Arcade" },
      { secret: "Mortal Kombat", hint: "Fatality" },
      { secret: "Call of Duty", hint: "Shooter" },
      { secret: "Halo", hint: "Spartan" },
      { secret: "Grand Theft Auto", hint: "Driving" },
      { secret: "The Sims", hint: "Simulation" },
      { secret: "Animal Crossing", hint: "Island" },
      { secret: "Super Smash Bros", hint: "Brawler" },
      { secret: "Final Fantasy", hint: "RPG" },
      { secret: "Overwatch", hint: "Team" },
      { secret: "Rocket League", hint: "Soccer-cars" },
      { secret: "Fall Guys", hint: "Obstacles" },
      { secret: "Among Us", hint: "Impostor" },
      { secret: "Guitar Hero", hint: "Rhythm" }
    ]
  },
  {
    id: "mythical_magic",
    name: "Mythical & Magic 🦄",
    icon: "🦄",
    words: [
      { secret: "Dragon", hint: "Fire" },
      { secret: "Unicorn", hint: "Horn" },
      { secret: "Wizard", hint: "Sorcery" },
      { secret: "Phoenix", hint: "Flames" },
      { secret: "Mermaid", hint: "Ocean" },
      { secret: "Genie", hint: "Wishes" },
      { secret: "Robot", hint: "Machine" },
      { secret: "Time Machine", hint: "Timeline" },
      { secret: "Alien Visitor", hint: "Space" },
      { secret: "Giant", hint: "Enormous" },
      { secret: "Superhero", hint: "Caped" },
      { secret: "Pirate Ship", hint: "Vessel" },
      { secret: "Vampire", hint: "Fangs" },
      { secret: "Werewolf", hint: "Fullmoon" },
      { secret: "Pegasus", hint: "Wings" },
      { secret: "Gargoyle", hint: "Stone" },
      { secret: "Sphinx", hint: "Riddle" },
      { secret: "Minotaur", hint: "Labyrinth" },
      { secret: "Cyclops", hint: "Eye" },
      { secret: "Centaur", hint: "Horse" },
      { secret: "Flying Carpet", hint: "Levitation" },
      { secret: "Spellbook", hint: "Incantation" },
      { secret: "Magic Mirror", hint: "Reflection" },
      { secret: "Kraken", hint: "Monster" },
      { secret: "Elves", hint: "Magic" },
      { secret: "Gnome", hint: "Garden" },
      { secret: "Goblin", hint: "Mischief" },
      { secret: "Troll", hint: "Bridge" },
      { secret: "Ogre", hint: "Swamp" },
      { secret: "Fairy", hint: "Pixie" },
      { secret: "Nymph", hint: "Nature" },
      { secret: "Siren", hint: "Singing" },
      { secret: "Hydra", hint: "Heads" },
      { secret: "Cerberus", hint: "Guard" },
      { secret: "Chimera", hint: "Hybrid" },
      { secret: "Griffin", hint: "Eagle-lion" },
      { secret: "Hippogriff", hint: "Horse-eagle" },
      { secret: "Basilisk", hint: "Gaze" },
      { secret: "Leviathan", hint: "Sea-monster" },
      { secret: "Behemoth", hint: "Colossal" },
      { secret: "Wendigo", hint: "Forest" },
      { secret: "Sasquatch", hint: "Footprint" },
      { secret: "Yeti", hint: "Snowman" },
      { secret: "Chupacabra", hint: "Goats" },
      { secret: "Banshee", hint: "Wail" },
      { secret: "Leprechaun", hint: "Gold" },
      { secret: "Valkyrie", hint: "Shieldmaiden" },
      { secret: "Banshee", hint: "Scream" },
      { secret: "Ghost", hint: "Apparition" },
      { secret: "Poltergeist", hint: "Haunting" },
      { secret: "Specter", hint: "Phantom" },
      { secret: "Mummy", hint: "Tomb" },
      { secret: "Zombie", hint: "Undead" },
      { secret: "Necromancer", hint: "Sorcerer" },
      { secret: "Sorceress", hint: "Enchantress" },
      { secret: "Warlock", hint: "Spells" },
      { secret: "Alchemist", hint: "Transmutation" },
      { secret: "Druid", hint: "Nature" },
      { secret: "Shaman", hint: "Spirits" },
      { secret: "Crystal Ball", hint: "Divination" },
      { secret: "Cauldron", hint: "Brewing" },
      { secret: "Magic Wand", hint: "Casting" },
      { secret: "Potion", hint: "Elixir" },
      { secret: "Amulet", hint: "Protection" },
      { secret: "Talisman", hint: "Charm" },
      { secret: "Enchanted Ring", hint: "Jewelry" },
      { secret: "Invisibility Cloak", hint: "Stealth" },
      { secret: "Broomstick", hint: "Flight" },
      { secret: "Philosopher's Stone", hint: "Immortality" },
      { secret: "Excalibur", hint: "Sword" },
      { secret: "Holy Grail", hint: "Chalice" },
      { secret: "Pandora's Box", hint: "Curse" },
      { secret: "Atlantis", hint: "Sunken" },
      { secret: "El Dorado", hint: "Gold" },
      { secret: "Shangri-La", hint: "Utopia" },
      { secret: "Valhalla", hint: "Hall" },
      { secret: "Mount Olympus", hint: "Gods" },
      { secret: "Underworld", hint: "Hades" },
      { secret: "Tree of Life", hint: "Yggdrasil" },
      { secret: "Fountain of Youth", hint: "Rejuvenation" },
      { secret: "Rune", hint: "Symbol" },
      { secret: "Spell", hint: "Incantation" },
      { secret: "Hex", hint: "Curse" },
      { secret: "Enchantment", hint: "Glamour" },
      { secret: "Teleportation", hint: "Portal" },
      { secret: "Telekinesis", hint: "Mind-power" },
      { secret: "Pyrokinesis", hint: "Fire-control" },
      { secret: "Shape-shifter", hint: "Transformation" },
      { secret: "Golem", hint: "Clay" },
      { secret: "Homunculus", hint: "Created" },
      { secret: "Jackalope", hint: "Antlers" },
      { secret: "Mothman", hint: "Cryptid" },
      { secret: "Jersey Devil", hint: "Folklore" },
      { secret: "Skinwalker", hint: "Legend" },
      { secret: "Thunderbird", hint: "Storm" },
      { secret: "Firebird", hint: "Slavic" },
      { secret: "Kitsune", hint: "Fox-spirit" },
      { secret: "Tengu", hint: "Demon" },
      { secret: "Dragonfly Fairy", hint: "Wings" },
      { secret: "Will-o'-the-wisp", hint: "Light" }
    ]
  },
  {
    id: "superheroes",
    name: "Superheroes 🦸‍♂️",
    icon: "🦸‍♂️",
    words: [
      { secret: "Spider-Man", hint: "Webs" },
      { secret: "Batman", hint: "Gotham" },
      { secret: "Superman", hint: "Krypton" },
      { secret: "Iron Man", hint: "Armor" },
      { secret: "Wonder Woman", hint: "Amazon" },
      { secret: "Captain America", hint: "Shield" },
      { secret: "Thor", hint: "Hammer" },
      { secret: "Black Panther", hint: "Wakanda" },
      { secret: "Hulk", hint: "Green" },
      { secret: "Flash", hint: "Speed" },
      { secret: "Aquaman", hint: "Ocean" },
      { secret: "Wolverine", hint: "Claws" },
      { secret: "Doctor Strange", hint: "Sorcerer" },
      { secret: "Ant-Man", hint: "Shrink" },
      { secret: "Star-Lord", hint: "Galaxy" },
      { secret: "Thanos", hint: "Gauntlet" },
      { secret: "Joker", hint: "Jester" },
      { secret: "Groot", hint: "Tree" },
      { secret: "Venom", hint: "Symbiote" },
      { secret: "Deadpool", hint: "Mercenary" },
      { secret: "Hawkeye", hint: "Archery" },
      { secret: "Scarlet Witch", hint: "Telekinesis" },
      { secret: "Supergirl", hint: "Caped" },
      { secret: "Green Lantern", hint: "Ring" },
      { secret: "Shazam", hint: "Lightning" },
      { secret: "Batgirl", hint: "Vigilante" },
      { secret: "Robin", hint: "Sidekick" },
      { secret: "Nightwing", hint: "Acrobat" },
      { secret: "Catwoman", hint: "Burglar" },
      { secret: "Harley Quinn", hint: "Mallet" },
      { secret: "Penguin", hint: "Umbrella" },
      { secret: "Riddler", hint: "Puzzles" },
      { secret: "Two-Face", hint: "Coin" },
      { secret: "Poison Ivy", hint: "Plants" },
      { secret: "Bane", hint: "Venom" },
      { secret: "Mr. Freeze", hint: "Ice" },
      { secret: "Green Goblin", hint: "Glider" },
      { secret: "Doctor Octopus", hint: "Tentacles" },
      { secret: "Carnage", hint: "Red" },
      { secret: "Daredevil", hint: "Blind" },
      { secret: "Punisher", hint: "Skull" },
      { secret: "Luke Cage", hint: "Unbreakable" },
      { secret: "Iron Fist", hint: "Martial-arts" },
      { secret: "Jessica Jones", hint: "Investigator" },
      { secret: "Moon Knight", hint: "Egyptian" },
      { secret: "Ghost Rider", hint: "Skull-fire" },
      { secret: "Blade", hint: "Vampire-hunter" },
      { secret: "Magneto", hint: "Magnetism" },
      { secret: "Professor X", hint: "Telepathy" },
      { secret: "Cyclops", hint: "Visor" },
      { secret: "Storm", hint: "Weather" },
      { secret: "Rogue", hint: "Absorb" },
      { secret: "Gambit", hint: "Cards" },
      { secret: "Beast", hint: "Blue" },
      { secret: "Jean Grey", hint: "Phoenix" },
      { secret: "Nightcrawler", hint: "Teleport" },
      { secret: "Iceman", hint: "Frost" },
      { secret: "Colossus", hint: "Steel" },
      { secret: "Mystique", hint: "Shifter" },
      { secret: "Deadpool", hint: "Swords" },
      { secret: "Falcon", hint: "Wings" },
      { secret: "Winter Soldier", hint: "Arm" },
      { secret: "War Machine", hint: "Heavy-artillery" },
      { secret: "Vision", hint: "Mind-stone" },
      { secret: "Black Widow", hint: "Spy" },
      { secret: "Captain Marvel", hint: "Cosmic" },
      { secret: "Ms. Marvel", hint: "Embiggen" },
      { secret: "Shang-Chi", hint: "Rings" },
      { secret: "She-Hulk", hint: "Attorney" },
      { secret: "Miles Morales", hint: "Venom-strike" },
      { secret: "Gwen Stacy", hint: "Spider-Gwen" },
      { secret: "Silver Surfer", hint: "Board" },
      { secret: "Galactus", hint: "World-eater" },
      { secret: "Doctor Doom", hint: "Latveria" },
      { secret: "Human Torch", hint: "Flame-on" },
      { secret: "Thing", hint: "Rock" },
      { secret: "Invisible Woman", hint: "Forcefield" },
      { secret: "Mister Fantastic", hint: "Stretch" },
      { secret: "Cyborg", hint: "Cybernetic" },
      { secret: "Starfire", hint: "Tamaran" },
      { secret: "Raven", hint: "Darkness" },
      { secret: "Beast Boy", hint: "Animals" },
      { secret: "Static Shock", hint: "Electricity" },
      { secret: "Martian Manhunter", hint: "Mars" },
      { secret: "Hawkman", hint: "Mace" },
      { secret: "Hawkgirl", hint: "Thanagar" },
      { secret: "Atom", hint: "Subatomic" },
      { secret: "Firestorm", hint: "Fusion" },
      { secret: "Black Canary", hint: "Scream" },
      { secret: "Green Arrow", hint: "Bow" },
      { secret: "Constantine", hint: "Occult" },
      { secret: "Swamp Thing", hint: "Elemental" },
      { secret: "Darkseid", hint: "Apokolips" },
      { secret: "Brainiac", hint: "Collector" },
      { secret: "Lex Luthor", hint: "Billionaire" },
      { secret: "General Zod", hint: "Kneel" },
      { secret: "Doomsday", hint: "Monster" },
      { secret: "Bizarro", hint: "Reverse" },
      { secret: "Sinestro", hint: "Yellow-ring" },
      { secret: "Black Adam", hint: "Kahndaq" }
    ]
  },
  {
    id: "bible_characters",
    name: "Bible Characters 📜",
    icon: "📜",
    words: [
      { secret: "Moses", hint: "Sea" },
      { secret: "Noah", hint: "Ark" },
      { secret: "David", hint: "Goliath" },
      { secret: "Daniel", hint: "Lions" },
      { secret: "Jonah", hint: "Whale" },
      { secret: "Adam", hint: "Garden" },
      { secret: "Eve", hint: "Apple" },
      { secret: "Abraham", hint: "Faith" },
      { secret: "Joseph", hint: "Coat" },
      { secret: "Samson", hint: "Strength" },
      { secret: "Esther", hint: "Queen" },
      { secret: "Solomon", hint: "Wisdom" },
      { secret: "Mary", hint: "Mother" },
      { secret: "Peter", hint: "Apostle" },
      { secret: "Paul", hint: "Letters" },
      { secret: "Joshua", hint: "Jericho" },
      { secret: "Ruth", hint: "Loyalty" },
      { secret: "Samuel", hint: "Prophet" },
      { secret: "Elijah", hint: "Chariot" },
      { secret: "Gideon", hint: "Fleece" },
      { secret: "Miriam", hint: "Tambourine" },
      { secret: "Lazarus", hint: "Resurrection" },
      { secret: "John the Baptist", hint: "Jordan" },
      { secret: "Sarah", hint: "Laughter" },
      { secret: "Job", hint: "Patience" },
      { secret: "Isaac", hint: "Promise" },
      { secret: "Jacob", hint: "Ladder" },
      { secret: "Rachel", hint: "Flocks" },
      { secret: "Leah", hint: "Matriarch" },
      { secret: "Aaron", hint: "Rod" },
      { secret: "Cain", hint: "Brother" },
      { secret: "Abel", hint: "Offering" },
      { secret: "Seth", hint: "Lineage" },
      { secret: "Enoch", hint: "Walked" },
      { secret: "Methuselah", hint: "Oldest" },
      { secret: "Lot", hint: "Salt" },
      { secret: "Rebekah", hint: "Well" },
      { secret: "Esau", hint: "Hairy" },
      { secret: "Deborah", hint: "Judge" },
      { secret: "Delilah", hint: "Shears" },
      { secret: "Boaz", hint: "Kinsman" },
      { secret: "Naomi", hint: "Bitterness" },
      { secret: "Hannah", hint: "Prayer" },
      { secret: "Eli", hint: "Priest" },
      { secret: "Saul", hint: "King" },
      { secret: "Jonathan", hint: "Covenant" },
      { secret: "Goliath", hint: "Giant" },
      { secret: "Absalom", hint: "Hair" },
      { secret: "Elisha", hint: "Mantle" },
      { secret: "Isaiah", hint: "Prophecy" },
      { secret: "Jeremiah", hint: "Weeping" },
      { secret: "Ezekiel", hint: "Bones" },
      { secret: "Hosea", hint: "Faithful" },
      { secret: "Joel", hint: "Locusts" },
      { secret: "Amos", hint: "Herdsman" },
      { secret: "Obadiah", hint: "Visions" },
      { secret: "Micah", hint: "Justice" },
      { secret: "Nahum", hint: "Nineveh" },
      { secret: "Habakkuk", hint: "Watchtower" },
      { secret: "Zephaniah", hint: "Day" },
      { secret: "Haggai", hint: "Temple" },
      { secret: "Zechariah", hint: "Branch" },
      { secret: "Malachi", hint: "Messenger" },
      { secret: "Shadrach", hint: "Furnace" },
      { secret: "Meshach", hint: "Fire" },
      { secret: "Abednego", hint: "Flames" },
      { secret: "Nebuchadnezzar", hint: "Babylon" },
      { secret: "Belshazzar", hint: "Writing" },
      { secret: "Darius", hint: "Decree" },
      { secret: "Cyrus", hint: "Persia" },
      { secret: "Mordecai", hint: "Purim" },
      { secret: "Haman", hint: "Gallows" },
      { secret: "Joseph of Nazareth", hint: "Carpenter" },
      { secret: "Elizabeth", hint: "Barren" },
      { secret: "Zechariah Priest", hint: "Mute" },
      { secret: "Simeon", hint: "Blessing" },
      { secret: "Anna", hint: "Prophetess" },
      { secret: "Andrew", hint: "Fisherman" },
      { secret: "James", hint: "Thunder" },
      { secret: "John", hint: "Beloved" },
      { secret: "Philip", hint: "Disciple" },
      { secret: "Bartholomew", hint: "Nathanael" },
      { secret: "Thomas", hint: "Doubting" },
      { secret: "Matthew", hint: "Tax-collector" },
      { secret: "Thaddaeus", hint: "Apostle" },
      { secret: "Simon the Zealot", hint: "Patriot" },
      { secret: "Judas Iscariot", hint: "Coins" },
      { secret: "Matthias", hint: "Chosen" },
      { secret: "Stephen", hint: "Martyr" },
      { secret: "Barnabas", hint: "Encourager" },
      { secret: "Timothy", hint: "Youth" },
      { secret: "Titus", hint: "Crete" },
      { secret: "Philemon", hint: "Slaveowner" },
      { secret: "Onesimus", hint: "Useful" },
      { secret: "Lydia", hint: "Purple" },
      { secret: "Priscilla", hint: "Tentmaker" },
      { secret: "Aquila", hint: "Fellow-worker" },
      { secret: "Dorcas", hint: "Tabitha" },
      { secret: "Cornelius", hint: "Centurion" },
      { secret: "Nicodemus", hint: "Night" }
    ]
  },
  {
    id: "cartoons_movies",
    name: "Cartoons & Movies 🎬",
    icon: "🎬",
    words: [
      { secret: "SpongeBob", hint: "Pineapple" },
      { secret: "Mickey Mouse", hint: "Disney" },
      { secret: "Elsa", hint: "Frozen" },
      { secret: "Shrek", hint: "Swamp" },
      { secret: "Scooby-Doo", hint: "Mystery" },
      { secret: "Woody", hint: "Cowboy" },
      { secret: "Buzz Lightyear", hint: "Space" },
      { secret: "Pikachu", hint: "Lightning" },
      { secret: "Minions", hint: "Yellow" },
      { secret: "Moana", hint: "Island" },
      { secret: "Simba", hint: "Lion" },
      { secret: "Garfield", hint: "Lasagna" },
      { secret: "Patrick Star", hint: "SeaStar" },
      { secret: "Bugs Bunny", hint: "Carrot" },
      { secret: "Lightning McQueen", hint: "Racecar" },
      { secret: "WALL-E", hint: "Robot" },
      { secret: "Stitch", hint: "Alien" },
      { secret: "Po the Panda", hint: "Noodles" },
      { secret: "Gru", hint: "Despicable" },
      { secret: "Sonic", hint: "Speed" },
      { secret: "Mario", hint: "Plumber" },
      { secret: "Toothless", hint: "Dragon" },
      { secret: "Dora", hint: "Explorer" },
      { secret: "Tom & Jerry", hint: "Chase" },
      { secret: "Winnie the Pooh", hint: "Honey" },
      { secret: "Donald Duck", hint: "Sailor" },
      { secret: "Goofy", hint: "Dog" },
      { secret: "Pluto", hint: "Hound" },
      { secret: "Cinderella", hint: "Slipper" },
      { secret: "Snow White", hint: "Dwarfs" },
      { secret: "Ariel", hint: "Mermaid" },
      { secret: "Belle", hint: "Beast" },
      { secret: "Jasmine", hint: "Aladdin" },
      { secret: "Mulan", hint: "Warrior" },
      { secret: "Rapunzel", hint: "Hair" },
      { secret: "Tiana", hint: "Frog" },
      { secret: "Mirabel", hint: "Encanto" },
      { secret: "Baymax", hint: "Inflatable" },
      { secret: "Nemo", hint: "Clownfish" },
      { secret: "Dory", hint: "Forgetful" },
      { secret: "Mater", hint: "Towtruck" },
      { secret: "Remy", hint: "Ratatouille" },
      { secret: "Sulley", hint: "Monster" },
      { secret: "Mike Wazowski", hint: "Eyeball" },
      { secret: "Incredibles", hint: "Family" },
      { secret: "Dash", hint: "Speedster" },
      { secret: "Jack-Jack", hint: "Baby" },
      { secret: "Joy", hint: "Emotion" },
      { secret: "Sadness", hint: "Blue" },
      { secret: "Bing Bong", hint: "Imaginary" },
      { secret: "Judy Hopps", hint: "Bunny" },
      { secret: "Nick Wilde", hint: "Fox" },
      { secret: "Olaf", hint: "Snowman" },
      { secret: "Kristoff", hint: "Reindeer" },
      { secret: "Maui", hint: "Hook" },
      { secret: "Peter Pan", hint: "Neverland" },
      { secret: "Tinker Bell", hint: "Pixie" },
      { secret: "Captain Hook", hint: "Pirate" },
      { secret: "Pinocchio", hint: "Puppet" },
      { secret: "Bambi", hint: "Deer" },
      { secret: "Dumbo", hint: "Ears" },
      { secret: "Tarzan", hint: "Vine" },
      { secret: "Hercules", hint: "Hero" },
      { secret: "Megamind", hint: "Blue" },
      { secret: "Despicable Me", hint: "Villain" },
      { secret: "The Lorax", hint: "Trees" },
      { secret: "Grinch", hint: "Christmas" },
      { secret: "Cat in the Hat", hint: "Stripes" },
      { secret: "Paddington Bear", hint: "Marmalade" },
      { secret: "Stuart Little", hint: "Mouse" },
      { secret: "Shrek's Donkey", hint: "Waffles" },
      { secret: "Puss in Boots", hint: "Zorro" },
      { secret: "Fiona", hint: "Ogre" },
      { secret: "Kung Fu Panda", hint: "Master" },
      { secret: "Madagascar Penguins", hint: "Operation" },
      { secret: "Alex the Lion", hint: "Central-Park" },
      { secret: "Marty the Zebra", hint: "Stripes" },
      { secret: "Snoopy", hint: "Beagle" },
      { secret: "Charlie Brown", hint: "Kite" },
      { secret: "Garfield", hint: "Odie" },
      { secret: "The Flintstones", hint: "Bedrock" },
      { secret: "The Jetsons", hint: "Future" },
      { secret: "Powerpuff Girls", hint: "Chemical-X" },
      { secret: "Dexter's Lab", hint: "Inventions" },
      { secret: "Johnny Bravo", hint: "Sunglasses" },
      { secret: "Courage the Cowardly Dog", hint: "Haunted" },
      { secret: "Ben 10", hint: "Omnitrix" },
      { secret: "Teen Titans", hint: "Tower" },
      { secret: "Phineas and Ferb", hint: "Summer" },
      { secret: "Perry the Platypus", hint: "Agent-P" },
      { secret: "Kim Possible", hint: "Communicator" },
      { secret: "Gravity Falls", hint: "Journal" },
      { secret: "Star Wars Yoda", hint: "Jedi" },
      { secret: "Darth Vader", hint: "Helmet" },
      { secret: "Luke Skywalker", hint: "Lightsaber" },
      { secret: "Chewbacca", hint: "Wookiee" },
      { secret: "R2-D2", hint: "Droid" },
      { secret: "Harry Potter", hint: "Scar" },
      { secret: "Hermione", hint: "Witch" },
      { secret: "Ron Weasley", hint: "Ginger" }
    ]
  }
];

if (typeof window !== 'undefined') {
  window.CATEGORIES = CATEGORIES;
}
